services:
  nginx-http:
    service_type: http
    project_name: default
    group_name: nginx-http
    instance_prefix: redis-cluster-
    instance_type: container
    lb_options:
      healthCheck:
        path: /
        interval: "10s"
        timeout: "3s"

  redis-cluster:
    service_type: tcp
    project_name: default
    group_name: redis-cluster
    instance_prefix: redis-cluster-
    instance_type: container
    port: 6379