services:
  nginx-backend:
    project_name: default
    group_name: svc-nginx
    instance_prefix: svc-nginx-
    instance_type: container

  nginx-frontend:
    project_name: default
    group_name: svc-nginx
    instance_prefix: svc-nginx-
    instance_type: container
